### ISSUE TITLE
Explanation of DRV entity missing in Readme

### ISSUE THREAD

**Issue by TacticalVilius** [ltgoslo/norne#1]
Hi,

Some entities in the dataset are tagged as "DRV". This entity is also present in the class distribution in the README file. However, there is no explanation of what this entity is.

Kind regards

**Comment by fredrijo** [comment]
Thank you! I have added `DRV` in the README now, see if it makes sense. I'll close this issue once you approve :)

**Comment by TacticalVilius** [comment]
Thanks for quick response, very approved ;)
